language: python
python:
  - "3.4"
# Use firefox with xvfb to run a browser for our FTs
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
# Install dependencies
install:
  - pip install -r requirements.txt

script:
# Functional tests
- python functional_tests.py
